name: Build and Deploy Docker Image

on:
  pull_request:
    types: [opened, synchronize, closed]
    branches:
      - main
  push:
    branches:
      - main

concurrency:
  group: deploy-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    if: (github.event_name == 'pull_request' && github.event.action != 'closed') || (github.event_name == 'push' && github.ref == 'refs/heads/main')
    environment: dockerhub

    steps:
      - name: Checkout repository 🛒
        uses: actions/checkout@v3

      - name: Log in to Docker Hub 🔐
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx ⚙️
        uses: docker/setup-buildx-action@v2

      - name: Set IMAGE_TAG ⚙️
        id: set_image_tag
        run: |
          if [ "${{ github.event_name }}" == "push" ] && [ "${{ github.ref }}" == "refs/heads/main" ]; then
            echo "IMAGE_TAG=main" >> $GITHUB_ENV
          else
            echo "IMAGE_TAG=pr-${{ github.head_ref }}" >> $GITHUB_ENV
          fi

      - name: Build and push Docker image 🏗️
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/forum:${{ env.IMAGE_TAG }}

  deploy:
    runs-on: ubuntu-latest
    if: (github.event_name == 'pull_request' && github.event.action != 'closed') || (github.event_name == 'push' && github.ref == 'refs/heads/main')
    needs: build_and_push
    environment: testing
    outputs:
      host: ${{ steps.set_vars.outputs.host }}

    steps:
      - name: Setup SSH key 🔑
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Set IMAGE TAG, PORT, Database Schema and Hostname ⚙️
        id: set_vars
        run: |
          if [ "${{ github.event_name }}" == "push" ] && [ "${{ github.ref }}" == "refs/heads/main" ]; then
            echo "IMAGE_TAG=main" >> $GITHUB_ENV
            echo "PORT=3000" >> $GITHUB_ENV
            echo "DATA_SCHEMA=main" >> $GITHUB_ENV
            echo "HOST=forum.${{ secrets.HOSTNAME }}" >> $GITHUB_ENV
          else
            SANITIZED_TAG=$(echo "${{ github.head_ref }}" | sed 's/ä/ae/g; s/ü/ue/g; s/ö/oe/g')
            echo "IMAGE_TAG=pr-$SANITIZED_TAG" >> $GITHUB_ENV
            echo "PORT=$((10000 + (${{ github.event.number }} % 100)))" >> $GITHUB_ENV
            username="${{ github.event.pull_request.user.login }}"
            DATABASE_SCHEMA="$(echo "$username" | tr -dc '[:alpha:]' | tr '[:upper:]' '[:lower:]')"
            echo "DATABASE_SCHEMA=$DATABASE_SCHEMA" >> $GITHUB_ENV
            echo "HOST=$SANITIZED_TAG.top22.${{ secrets.HOSTNAME }}" >> $GITHUB_ENV
          fi

      - name: Deploy to VPS 🚀
        run: |
          CONTAINER_NAME=forum-${{ env.IMAGE_TAG }}
          ssh -o StrictHostKeyChecking=no -p 22 ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} "\
            DATABASE_IP=$(sudo docker container inspect postgres | jq -r '.[].NetworkSettings.Networks.db_default.IPAddress')
            DATABASE_URL=postgresql://${{ secrets.DATABASE_USER }}:${{ secrets.DATABASE_PASSWORD }}@$DATABASE_IP:5432/top22?schema=${{ env.DATABASE_SCHEMA }}
            sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/forum:${{ env.IMAGE_TAG }} && \
            sudo docker stop $CONTAINER_NAME || true && \
            sudo docker rm $CONTAINER_NAME || true && \
            sudo docker run -d \
              --name $CONTAINER_NAME \
              --restart always \
              --network=proxy_default \
              -p ${{ env.PORT }}:3000 \
              -e DATABASE_URL=$DATABASE_URL \
              -e VIRTUAL_HOST=${{ env.HOST }} \
              -e LETSENCRYPT_HOST=${{ env.HOST }} \
              -e LETSENCRYPT_EMAIL=${{ secrets.LETSENCRYPT_EMAIL }} \
              ${{ secrets.DOCKERHUB_USERNAME }}/forum:${{ env.IMAGE_TAG }} && \
            sudo docker network connect db_default $CONTAINER_NAME"

      - name: Update Pull Request Description 📝
        uses: tzkhan/pr-update-action@v2
        with:
          head-branch-regex: ${{ github.head_ref }}
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          body-template: |
            [![.github/workflows/docker-deploy.yaml]
              (https://github.com/top-22/forum/actions/workflows/docker-deploy.yaml/badge.svg)]
            (https://${{ env.HOST }})"
          body-update-action: prefix

  update_database:
    runs-on: ubuntu-latest
    if: (github.event_name == 'push' && github.ref == 'refs/heads/main')
    needs: deploy

    steps:
      - name: Checkout repository 🛒
        uses: actions/checkout@v3

      - name: Set up Node.js 16.x 📥
        uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - name: Install dependencies 📦
        run: |
          yarn install

      - name: Fill .env file 📄
        run: |
          echo "DATABASE_URL=postgresql://${{ secrets.DATABASE_USER }}:${{ secrets.DATABASE_PASSWORD }}@localhost:5432/top22?schema=main" >> .env

      - name: Migrate database ⏩
        run: |
          npx prisma db push --force-reset

      - name: Fill database with test data 📝
        run: |
          yarn testdata

  remove_container:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' && github.event.action == 'closed'

    steps:
      - name: Setup SSH key 🔑
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Remove container from VPS 🗑️
        run: |
          ssh -o StrictHostKeyChecking=no -p 22 ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} "\
            sudo docker stop forum-pr-${{ github.head_ref }} || true && \
            sudo docker rm forum-pr-${{ github.head_ref }} || true && \
            sudo docker rmi ${{ secrets.DOCKERHUB_USERNAME }}/forum:pr-${{ github.head_ref }} || true"

      - name: Remove image from Docker Hub 🗑️
        run: |
          TOKEN=$(
                  curl -s -H "Content-Type: application/json" -X POST \
                  -d "{\"username\": \"${{ secrets.DOCKERHUB_USERNAME }}\", \"password\": \"${{ secrets.DOCKERHUB_TOKEN }}\"}" \
                  https://hub.docker.com/v2/users/login/ | jq -r .token
                  )
          IMAGE_TAG=pr-${{ github.head_ref }}
          curl "https://hub.docker.com/v2/repositories/${{ secrets.DOCKERHUB_USERNAME }}/forum/tags/$IMAGE_TAG/" \
                  -X DELETE \
                  -H "Authorization: JWT ${TOKEN}"
