name: Build and Deploy Docker Image

on:
  push:
    branches:
      - main

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    environment: build_and_push

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/forum:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build_and_push
    environment: deploy

    steps:
      - name: Setup SSH key
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to VPS
        run: |
          ssh -o StrictHostKeyChecking=no -p {{ secrets.SSH_PORT }} {{ secrets.VPS_USERNAME }}@${{ secrets.VPS_IP }} << 'ENDSSH'
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/forum:latest
            docker stop forum || true
            docker rm forum || true
            docker run -d \
              --name forum \
              --restart always \
              -p 3000:3000 \
              -e DATABASE_URL=${{ secrets.DATABASE_URL }} \
              ${{ secrets.DOCKERHUB_USERNAME }}/forum:latest
